export const PRICE_LIST = [
  "Lista de precios AMP",
  "Lista de precios Amphenol",
  "Lista de precios Andrew",
  "Lista de precios APC",
  "Lista de precios CISCO",
  "Lista de precios D-Link",
  "Lista de precios Dixon",
  "Lista de precios Energit",
  "Lista de precios Fibra",
  "Lista de precios HP",
  "Lista de precios Mikrotik",
  "Lista de precios Nexxt Solutions",
  "Lista de precios Panduit",
  "Lista de precios Teldor",
  "Lista de precios TRENDnet",
  "Lista de precios Siemon",
  "Lista de precios Ubiquiti",
];

export const SOLUTIONS = [
  "Access Point",
  "Antenas MIMO",
  "Antenas de Panel",
  "Antenas Sectoriales",
  "Cable Pigtail",
  "Media Converter",
  "Soporte Tecnico",
  "Acerca de Nosotros",
];

export const PRODUCT_RB750 = {
  title: "RouterBOARD con 5 puertos Ethernet MIKROTIK RB750",
  applications: {
    0: "Interconecte sucursales y oficinas de empresas pï¿½blicas y privadas(Wireless LAN).",
    1: "Provee servicios de internet inalï¿½mbrico.",
    2: "(ISP inalï¿½mbrico).",
    3: "Sistemas WiFi.",
  },
  superiorPerformance: {
    0: "El RouterBOARD  MIKROTIK RB750 es un pequeï¿½o router que viene con cinco puertos Ethernet, en una caja de plï¿½stico.",
    1: "De diseï¿½o atractivo todo lo que buscan en una unidad pequeï¿½a SOHO, su precio es menor que la licencia RouterOS, es perfecto para administrar su red de cable en casa, el RB750 lo tiene todo.",
    2: "No sï¿½lo es econï¿½mico, es pequeï¿½a y fï¿½cil de usar.  Es probable que sea router MPLS mï¿½s econï¿½mico en el mercado.  No hay compromiso entre el precio y caracterï¿½sticas el RB750 tiene ambas cosas.  Con su diseï¿½o compacto y un aspecto limpio, se ajustarï¿½ perfectamente a su entorno SOHO.",
  },
  advantages: {
    0: "Pequeï¿½o y compacto.",
    1: "Caja de plï¿½stico blanca.",
    2: "Cinco puertos Ethernet.",
    3: "Increï¿½blemente rï¿½pido.",
  },
  download: {
    0: "Datos Tï¿½cnicos",
    1: "Guï¿½a de Instalaciï¿½n rï¿½pida",
  },
  technicalSpecifications: {
    codigoProducto: "RB750",
    monitoreoCorriente: "No",
    consumoMaximoEnergia: "2.5 Watt",
    velocidadCPU: "680 MHz",
    ram: "32 Mb",
    arquitectura: "MIPS-BE",
    puertosLAN: 5,
    gigabit: 0,
    miniPCI: 0,
    wirelessIntegrado: 0,
    usb: 0,
    tarjetaMemoria: 0,
    powerJack: "10 - 28 V",
    soporte802_3af: "No",
    poe: "10 - 28 V",
    monitorVoltaje: "No",
    temperaturaCPUmonitor: "No",
    pcbMonitorTemperatura: "Si",
    dimensiones: "214x86mm",
    rangoTemperatura: "-40° a +55° C",
    licenciaRouterOS: "Nivel 4",
  },
  PerformanceResults: [
    {
      ipFirewall: "off",
      conntrack: "off",
      modo: "Puente",
      mbps1: 47.1,
      fps1: 92000,
      mbps2: 358.4,
      fps2: 87500,
      mbps3: 452.97,
      fps3: 37300,
    },
    {
      ipFirewall: "on",
      conntrack: "off",
      modo: "Enrutamiento",
      mbps1: 37.68,
      fps1: 73600,
      mbps2: 294.91,
      fps2: 72000,
      mbps3: 452.97,
      fps3: 37300,
    },
    {
      ipFirewall: "on",
      conntrack: "off",
      modo: "Puente",
      mbps1: 35.48,
      fps1: 69300,
      mbps2: 230.2,
      fps2: 56200,
      mbps3: 446.9,
      fps3: 36800,
    },
    {
      ipFirewall: "on",
      conntrack: "on",
      modo: "Enrutamiento",
      mbps1: 28.42,
      fps1: 55500,
      mbps2: 222.41,
      fps2: 54300,
      mbps3: 445.68,
      fps3: 36700,
    },
    {
      ipFirewall: "on",
      conntrack: "on",
      modo: "Puente",
      mbps1: 18.94,
      fps1: 37000,
      mbps2: 149.5,
      fps2: 36500,
      mbps3: 425.04,
      fps3: 35000,
    },
  ],
};
